### PR TITLE
Allows to set multicore and mc.cores for phangorn::bootstrap.pml

### PR DESCRIPTION
**Pull request by amizeranschi**
Implements https://github.com/josephwb/chronos/issues/5

### CODE REVIEW

**Comment by josephwb** [comment]
Thanks for this @amizeranschi.

I've used multicore in the past, but it was very strict in its use: it requires a POSIX-compliant OS (i.e NOT Windows). Is this still the case?

Also, when I searched up multicore I see [it has been removed from CRAN](https://cran.r-project.org/web/packages/multicore/index.html), and the package `parallel` is suggested in its place.

**Comment by amizeranschi** [comment]
Hi @josephwb 

Yes, you're right, the `parallel` package is one way to go about it. Actually, this is what `phangorn::bootstrap.pml()` uses, as well:
https://github.com/KlausVigo/phangorn/blob/master/R/bootstrap.R#L148

https://www.rdocumentation.org/packages/parallel/versions/3.4.0/topics/mclapply

In this PR I've merely enabled this functionality, which was already available at the level of `phangorn`. However, it would be greatto have something similar at the level of `chronos::chronosCI`, as well.

I found another promising CRAN package called `future.apply`, which implements a parallel version of `sapply()`:
https://cran.r-project.org/web/packages/future.apply/future.apply.pdf#Rfn.future.Rul.sapply

Would you be able to test if this makes a difference in `chronos::chronosCI()` at the "chronos bootstrap" phase?
https://github.com/josephwb/chronos/blob/master/R/chronosCI.R#L167

**Comment by KlausVigo** [comment]
Hi @amizeranschi and @josephwb, 
the problem with parallelizing is that it depends on your hardware and operating system, so there is a lot of responsibility on the user side! For matrix algebra your R installation might even work already parallel. This depends which BLAS library you have installed on your machine (e.g. Intel MKL, OpenBLAS, ATLAS). See for example [https://csantill.github.io/RPerformanceWBLAS/](https://csantill.github.io/RPerformanceWBLAS/)  or
[https://brettklamer.com/diversions/statistical/faster-blas-in-r/](https://brettklamer.com/diversions/statistical/faster-blas-in-r/).
The future approach seems quite nice as it hides all the difficult and fiddly parts and you have one interface. However the user has to tell what approach to use. 
There are also some trade-offs, while many computers have now many cores, you also might make many copies of your data and run out of memory instead. And if you use parallel BLAS together with `mclapply` this might collide and slow things down.

**Comment by amizeranschi** [comment]
Hi @KlausVigo 

Thank you for your comments. I am running my codes on a 64-core Linux machine with 256 GB of RAM, using R 4.2.1 and OpenBLAS 0.3.23. Using this setup, I ran `chronos::chronosCI()` on a rooted tree with 692 tips and 327 internal nodes and it took 18 hours to run with the default `B = 100`.

Any advice for speeding things up would be much appreciated. I can also provide my data, in case it might be useful.

**Comment by KlausVigo** [comment]
Hi @amizeranschi
it is probably worth to look what are exactly the bottlenecks. 
Can you please run:   
```
Rprof(tmp <- tempfile(), memory.profiling = TRUE)
chronosCI(..., B=3)  #your proper code here
Rprof()
debug <- summaryRprof(tmp, memory = "both")
unlink(tmp)
debug
```
And send me the output of debug. Often there are surprising bottle necks and some easy fixes. Sometimes these change depending on the size of the datasets. You can reduce the number of bootstraps to as I suggested to 3 or 5 for the large dataset. You might run it also for a smaller data set with more bootstraps. These need run only a few minutes.  
 There is also the possibility of `line.profiling` to see which are the lines most time is spent in, but I am not sure if this option is always switched on.    

Can you check how many cores are used (e.g. htop). 

> Hi @KlausVigo
> 
> Thank you for your comments. I am running my codes on a 64-core Linux machine with 256 GB of RAM, using R 4.2.1 and OpenBLAS 0.3.23. Using this setup, I ran `chronos::chronosCI()` on a rooted tree with 692 tips and 327 internal nodes and it took 18 hours to run with the default `B = 100`.
> 
> Any advice for speeding things up would be much appreciated. I can also provide my data, in case it might be useful.

**Comment by amizeranschi** [comment]
During the `Running chronos bootstrap` phase of `chronos::chronosCI()`, only one core is actively working (near 100% usage), as seen in `htop`. The same goes for the `Running phangorn bootstrap...` phase. For the latter, I remembered that `phangorn::bootstrap.pml()` has the possibility to run in parallel, by setting `multicore = T` and `mc.cores = 64`. In previous tests of that function, setting those parameters resulted in great speed-ups on my hardware and I could see all cores working at near 100% in `htop` as well.

Thus, the reason of this PR was to enable that functionality at the level of the `Running phangorn bootstrap...` stage in `chronos::chronosCI()`. Using my full dataset and 100 bootstraps, it reduces the running time of that stage from several hours to only a few minutes, on my machine. It's true that not all users will be able to benefit from this, but for those who do, it could make a difference.

@KlausVigo I have also run the code you suggested, with 3 bootstraps, and I'm pasting the output below.

```
$by.self
                    self.time self.pct total.time total.pct mem.total
"log.lik.poisson"     1519.14    70.46    1915.06     88.82 1329046.2
"isTRUE"               266.36    12.35     327.86     15.21  242734.2
".Call"                178.94     8.30    2136.90     99.11 1462651.2
"sum"                   68.62     3.18      68.62      3.18   54134.5
"any"                   56.26     2.61      56.26      2.61   44924.9
"objective"             24.06     1.12    1956.86     90.76 1361843.4
"penal.loglik"          17.74     0.82    1932.80     89.65 1342413.7
"pml.fit4"               4.94     0.23      34.82      1.62   16211.9
"is.na"                  3.42     0.16       3.42      0.16    2584.7
"$"                      2.48     0.12       2.48      0.12    1395.3
"f"                      2.46     0.11      27.92      1.29   13956.3
"length"                 1.98     0.09       1.98      0.09    1540.3
"which"                  1.40     0.06       1.72      0.08     863.5
"optimRooted"            0.84     0.04      46.96      2.18   22852.4
"$<-"                    0.76     0.04       0.76      0.04     398.7
"as.double"              0.60     0.03       0.60      0.03     294.4
"getCallingDLLe"         0.56     0.03       1.10      0.05     636.2
"optRoot0"               0.52     0.02       9.24      0.43    4384.5
"pml.move"               0.52     0.02       4.56      0.21    2290.2
"get0"                   0.50     0.02       0.50      0.02     277.5
"attr"                   0.44     0.02       0.44      0.02     243.5
"<Anonymous>"            0.40     0.02      47.06      2.18   22880.2
".External2"             0.24     0.01      24.68      1.14   12219.5
"fft"                    0.24     0.01       0.24      0.01     130.9
"optimize"               0.22     0.01      28.86      1.34   14485.0
"dnorm"                  0.20     0.01       0.20      0.01      95.2
"rle"                    0.16     0.01       0.34      0.02     206.4
"pmax.int"               0.16     0.01       0.16      0.01      78.4
"seq.int"                0.16     0.01       0.16      0.01      63.3
"density.default"        0.14     0.01       1.36      0.06     685.2
"cbind"                  0.14     0.01       0.14      0.01      54.8
"unique.default"         0.12     0.01       0.12      0.01      50.9
"approx"                 0.10     0.00       0.34      0.02     185.9
"c"                      0.10     0.00       0.10      0.00      40.2
"diff.default"           0.08     0.00       0.08      0.00      53.6
"stopifnot"              0.06     0.00       0.08      0.00      37.8
"as.integer"             0.06     0.00       0.06      0.00      44.3
"ape::chronos"           0.04     0.00    2106.74     97.72 1449217.8
"getDensel"              0.04     0.00       1.88      0.09     982.4
"structure"              0.04     0.00       0.44      0.02     251.2
"diff"                   0.04     0.00       0.26      0.01     158.1
"unique"                 0.04     0.00       0.16      0.01      80.3
"Cdensel"                0.04     0.00       0.08      0.00      22.7
"pmax"                   0.04     0.00       0.08      0.00      37.6
"match.arg"              0.04     0.00       0.06      0.00      35.9
"dim"                    0.04     0.00       0.04      0.00      24.4
"list"                   0.04     0.00       0.04      0.00      27.0
"min"                    0.04     0.00       0.04      0.00      13.8
"reorderRcpp"            0.04     0.00       0.04      0.00       2.6
"FUN"                    0.02     0.00      47.28      2.19   22945.5
"isUnimodal"             0.02     0.00       0.34      0.02     207.0
"regularize.values"      0.02     0.00       0.20      0.01     106.1
"%in%"                   0.02     0.00       0.04      0.00      28.5
"paste0"                 0.02     0.00       0.04      0.00      16.6
"Siblings"               0.02     0.00       0.04      0.00      19.1
"sort.int"               0.02     0.00       0.04      0.00      26.3
".deparseOpts"           0.02     0.00       0.02      0.00      13.0
"all"                    0.02     0.00       0.02      0.00      13.4
"allChildrenCPP"         0.02     0.00       0.02      0.00       9.6
"cumsum"                 0.02     0.00       0.02      0.00       0.0
"double"                 0.02     0.00       0.02      0.00       0.0
"eval"                   0.02     0.00       0.02      0.00      13.0
"match.fun"              0.02     0.00       0.02      0.00      12.7
"minEdge"                0.02     0.00       0.02      0.00       2.6
"mode"                   0.02     0.00       0.02      0.00      14.7
"pairlist"               0.02     0.00       0.02      0.00       7.9
"pmin"                   0.02     0.00       0.02      0.00      12.2
"prop_part2"             0.02     0.00       0.02      0.00       7.7
"storage.mode"           0.02     0.00       0.02      0.00      11.0

$by.total
                          total.time total.pct mem.total self.time self.pct
"chronos::chronosCI"         2156.00    100.00 1473186.3      0.00     0.00
".Call"                      2136.90     99.11 1462651.2    178.94     8.30
"ape::chronos"               2106.74     97.72 1449217.8      0.04     0.00
"nlminb"                     2106.64     97.71 1449153.4      0.00     0.00
"objective"                  1956.86     90.76 1361843.4     24.06     1.12
"penal.loglik"               1932.80     89.65 1342413.7     17.74     0.82
"log.lik.poisson"            1915.06     88.82 1329046.2   1519.14    70.46
"isTRUE"                      327.86     15.21  242734.2    266.36    12.35
"sum"                          68.62      3.18   54134.5     68.62     3.18
"any"                          56.26      2.61   44924.9     56.26     2.61
"FUN"                          47.28      2.19   22945.5      0.02     0.00
"lapply"                       47.20      2.19   22917.7      0.00     0.00
"phangorn::bootstrap.pml"      47.10      2.18   22886.5      0.00     0.00
"<Anonymous>"                  47.06      2.18   22880.2      0.40     0.02
"do.call"                      47.06      2.18   22880.2      0.00     0.00
"optimRooted"                  46.96      2.18   22852.4      0.84     0.04
"opt_Edge"                     46.96      2.18   22852.4      0.00     0.00
"pml.fit4"                     34.82      1.62   16211.9      4.94     0.23
"optimize"                     28.86      1.34   14485.0      0.22     0.01
"f"                            27.92      1.29   13956.3      2.46     0.11
".External2"                   24.68      1.14   12219.5      0.24     0.01
"optRoot0"                      9.24      0.43    4384.5      0.52     0.02
"pml.move"                      4.56      0.21    2290.2      0.52     0.02
"is.na"                         3.42      0.16    2584.7      3.42     0.16
"$"                             2.48      0.12    1395.3      2.48     0.12
"scaleEdges"                    2.08      0.10     471.0      0.00     0.00
"length"                        1.98      0.09    1540.3      1.98     0.09
"getDensel"                     1.88      0.09     982.4      0.04     0.00
"which"                         1.72      0.08     863.5      1.40     0.06
"density.default"               1.36      0.06     685.2      0.14     0.01
"stats::density"                1.36      0.06     685.2      0.00     0.00
"getCallingDLLe"                1.10      0.05     636.2      0.56     0.03
"$<-"                           0.76      0.04     398.7      0.76     0.04
"as.double"                     0.60      0.03     294.4      0.60     0.03
"get0"                          0.50      0.02     277.5      0.50     0.02
"attr"                          0.44      0.02     243.5      0.44     0.02
"structure"                     0.44      0.02     251.2      0.04     0.00
"rle"                           0.34      0.02     206.4      0.16     0.01
"approx"                        0.34      0.02     185.9      0.10     0.00
"isUnimodal"                    0.34      0.02     207.0      0.02     0.00
"diff"                          0.26      0.01     158.1      0.04     0.00
"fft"                           0.24      0.01     130.9      0.24     0.01
"dnorm"                         0.20      0.01      95.2      0.20     0.01
"regularize.values"             0.20      0.01     106.1      0.02     0.00
"quantile.default"              0.20      0.01      91.6      0.00     0.00
"pmax.int"                      0.16      0.01      78.4      0.16     0.01
"seq.int"                       0.16      0.01      63.3      0.16     0.01
"unique"                        0.16      0.01      80.3      0.04     0.00
"cbind"                         0.14      0.01      54.8      0.14     0.01
"unique.default"                0.12      0.01      50.9      0.12     0.01
"IQR"                           0.12      0.01      63.9      0.00     0.00
"quantile"                      0.12      0.01      63.9      0.00     0.00
"stats::bw.nrd0"                0.12      0.01      63.9      0.00     0.00
"c"                             0.10      0.00      40.2      0.10     0.00
"pml.fit"                       0.10      0.00      23.6      0.00     0.00
"diff.default"                  0.08      0.00      53.6      0.08     0.00
"stopifnot"                     0.08      0.00      37.8      0.06     0.00
"Cdensel"                       0.08      0.00      22.7      0.04     0.00
"pmax"                          0.08      0.00      37.6      0.04     0.00
"apply"                         0.08      0.00      27.7      0.00     0.00
"update.pml"                    0.08      0.00      14.4      0.00     0.00
"as.integer"                    0.06      0.00      44.3      0.06     0.00
"match.arg"                     0.06      0.00      35.9      0.04     0.00
"deparse"                       0.06      0.00      41.4      0.00     0.00
"deparse1"                      0.06      0.00      41.4      0.00     0.00
"paste"                         0.06      0.00      41.4      0.00     0.00
"prop.part"                     0.06      0.00      10.3      0.00     0.00
"rbl"                           0.06      0.00      38.9      0.00     0.00
"dim"                           0.04      0.00      24.4      0.04     0.00
"list"                          0.04      0.00      27.0      0.04     0.00
"min"                           0.04      0.00      13.8      0.04     0.00
"reorderRcpp"                   0.04      0.00       2.6      0.04     0.00
"%in%"                          0.04      0.00      28.5      0.02     0.00
"paste0"                        0.04      0.00      16.6      0.02     0.00
"Siblings"                      0.04      0.00      19.1      0.02     0.00
"sort.int"                      0.04      0.00      26.3      0.02     0.00
".reorder_ape"                  0.04      0.00       2.6      0.00     0.00
"ape::makeNodeLabel"            0.04      0.00       2.6      0.00     0.00
"format_perc"                   0.04      0.00      16.6      0.00     0.00
"makeNodeLabel.phylo"           0.04      0.00       2.6      0.00     0.00
"reorder.multiPhylo"            0.04      0.00       2.6      0.00     0.00
"reorder"                       0.04      0.00       2.6      0.00     0.00
"sort.default"                  0.04      0.00      26.3      0.00     0.00
"sort"                          0.04      0.00      26.3      0.00     0.00
"update"                        0.04      0.00       6.3      0.00     0.00
".deparseOpts"                  0.02      0.00      13.0      0.02     0.00
"all"                           0.02      0.00      13.4      0.02     0.00
"allChildrenCPP"                0.02      0.00       9.6      0.02     0.00
"cumsum"                        0.02      0.00       0.0      0.02     0.00
"double"                        0.02      0.00       0.0      0.02     0.00
"eval"                          0.02      0.00      13.0      0.02     0.00
"match.fun"                     0.02      0.00      12.7      0.02     0.00
"minEdge"                       0.02      0.00       2.6      0.02     0.00
"mode"                          0.02      0.00      14.7      0.02     0.00
"pairlist"                      0.02      0.00       7.9      0.02     0.00
"pmin"                          0.02      0.00      12.2      0.02     0.00
"prop_part2"                    0.02      0.00       7.7      0.02     0.00
"storage.mode"                  0.02      0.00      11.0      0.02     0.00
"allChildren"                   0.02      0.00       9.6      0.00     0.00
"ape::drop.tip"                 0.02      0.00       7.7      0.00     0.00
"ape::root"                     0.02      0.00       7.7      0.00     0.00
"formatC"                       0.02      0.00      11.0      0.00     0.00
"pml.control"                   0.02      0.00       9.9      0.00     0.00
"root.phylo"                    0.02      0.00       7.7      0.00     0.00
"vapply"                        0.02      0.00      12.7      0.00     0.00

$sample.interval
[1] 0.02

$sampling.time
[1] 2156
```

**Comment by KlausVigo** [comment]
> The same goes for the `Running phangorn bootstrap...` phase. For the latter, I remembered that `phangorn::bootstrap.pml()` has the possibility to run in parallel, by setting `multicore = T` and `mc.cores = 64`. In previous tests of that function, setting those parameters resulted in great speed-ups on my hardware and I could see all cores working at near 100% in `htop` as well.

In this parallelizing `bootstrap.pml` should work as you suggested. I would leave a few cores available (not use all 64). The problem is that could run out of memory or have problems  multicore that and OpenBLAS compete for the same cores.    
The other candidate to improve is `ape::chronos`, if you look at the output. The problem is that rates and edge lengths are only identifiable if one adds some penalization. Rates and edge lengths they are highly correlated the optimisation and especially for larger trees convergence is very slow. But this would need a total rewrite of the function.   

> During the `Running chronos bootstrap` phase of `chronos::chronosCI()`, only one core is actively working (near 100% usage), as seen in `htop`. The same goes for the `Running phangorn bootstrap...` phase. For the latter, I remembered that `phangorn::bootstrap.pml()` has the possibility to run in parallel, by setting `multicore = T` and `mc.cores = 64`. In previous tests of that function, setting those parameters resulted in great speed-ups on my hardware and I could see all cores working at near 100% in `htop` as well.
> 
> Thus, the reason of this PR was to enable that functionality at the level of the `Running phangorn bootstrap...` stage in `chronos::chronosCI()`. Using my full dataset and 100 bootstraps, it reduces the running time of that stage from several hours to only a few minutes, on my machine. It's true that not all users will be able to benefit from this, but for those who do, it could make a difference.
> 
> @KlausVigo I have also run the code you suggested, with 3 bootstraps, and I'm pasting the output below.
> 
> ```
> $by.self
>                     self.time self.pct total.time total.pct mem.total
> "log.lik.poisson"     1519.14    70.46    1915.06     88.82 1329046.2
> "isTRUE"               266.36    12.35     327.86     15.21  242734.2
> ".Call"                178.94     8.30    2136.90     99.11 1462651.2
> "sum"                   68.62     3.18      68.62      3.18   54134.5
> "any"                   56.26     2.61      56.26      2.61   44924.9
> "objective"             24.06     1.12    1956.86     90.76 1361843.4
> "penal.loglik"          17.74     0.82    1932.80     89.65 1342413.7
> "pml.fit4"               4.94     0.23      34.82      1.62   16211.9
> "is.na"                  3.42     0.16       3.42      0.16    2584.7
> "$"                      2.48     0.12       2.48      0.12    1395.3
> "f"                      2.46     0.11      27.92      1.29   13956.3
> "length"                 1.98     0.09       1.98      0.09    1540.3
> "which"                  1.40     0.06       1.72      0.08     863.5
> "optimRooted"            0.84     0.04      46.96      2.18   22852.4
> "$<-"                    0.76     0.04       0.76      0.04     398.7
> "as.double"              0.60     0.03       0.60      0.03     294.4
> "getCallingDLLe"         0.56     0.03       1.10      0.05     636.2
> "optRoot0"               0.52     0.02       9.24      0.43    4384.5
> "pml.move"               0.52     0.02       4.56      0.21    2290.2
> "get0"                   0.50     0.02       0.50      0.02     277.5
> "attr"                   0.44     0.02       0.44      0.02     243.5
> "<Anonymous>"            0.40     0.02      47.06      2.18   22880.2
> ".External2"             0.24     0.01      24.68      1.14   12219.5
> "fft"                    0.24     0.01       0.24      0.01     130.9
> "optimize"               0.22     0.01      28.86      1.34   14485.0
> "dnorm"                  0.20     0.01       0.20      0.01      95.2
> "rle"                    0.16     0.01       0.34      0.02     206.4
> "pmax.int"               0.16     0.01       0.16      0.01      78.4
> "seq.int"                0.16     0.01       0.16      0.01      63.3
> "density.default"        0.14     0.01       1.36      0.06     685.2
> "cbind"                  0.14     0.01       0.14      0.01      54.8
> "unique.default"         0.12     0.01       0.12      0.01      50.9
> "approx"                 0.10     0.00       0.34      0.02     185.9
> "c"                      0.10     0.00       0.10      0.00      40.2
> "diff.default"           0.08     0.00       0.08      0.00      53.6
> "stopifnot"              0.06     0.00       0.08      0.00      37.8
> "as.integer"             0.06     0.00       0.06      0.00      44.3
> "ape::chronos"           0.04     0.00    2106.74     97.72 1449217.8
> "getDensel"              0.04     0.00       1.88      0.09     982.4
> "structure"              0.04     0.00       0.44      0.02     251.2
> "diff"                   0.04     0.00       0.26      0.01     158.1
> "unique"                 0.04     0.00       0.16      0.01      80.3
> "Cdensel"                0.04     0.00       0.08      0.00      22.7
> "pmax"                   0.04     0.00       0.08      0.00      37.6
> "match.arg"              0.04     0.00       0.06      0.00      35.9
> "dim"                    0.04     0.00       0.04      0.00      24.4
> "list"                   0.04     0.00       0.04      0.00      27.0
> "min"                    0.04     0.00       0.04      0.00      13.8
> "reorderRcpp"            0.04     0.00       0.04      0.00       2.6
> "FUN"                    0.02     0.00      47.28      2.19   22945.5
> "isUnimodal"             0.02     0.00       0.34      0.02     207.0
> "regularize.values"      0.02     0.00       0.20      0.01     106.1
> "%in%"                   0.02     0.00       0.04      0.00      28.5
> "paste0"                 0.02     0.00       0.04      0.00      16.6
> "Siblings"               0.02     0.00       0.04      0.00      19.1
> "sort.int"               0.02     0.00       0.04      0.00      26.3
> ".deparseOpts"           0.02     0.00       0.02      0.00      13.0
> "all"                    0.02     0.00       0.02      0.00      13.4
> "allChildrenCPP"         0.02     0.00       0.02      0.00       9.6
> "cumsum"                 0.02     0.00       0.02      0.00       0.0
> "double"                 0.02     0.00       0.02      0.00       0.0
> "eval"                   0.02     0.00       0.02      0.00      13.0
> "match.fun"              0.02     0.00       0.02      0.00      12.7
> "minEdge"                0.02     0.00       0.02      0.00       2.6
> "mode"                   0.02     0.00       0.02      0.00      14.7
> "pairlist"               0.02     0.00       0.02      0.00       7.9
> "pmin"                   0.02     0.00       0.02      0.00      12.2
> "prop_part2"             0.02     0.00       0.02      0.00       7.7
> "storage.mode"           0.02     0.00       0.02      0.00      11.0
> 
> $by.total
>                           total.time total.pct mem.total self.time self.pct
> "chronos::chronosCI"         2156.00    100.00 1473186.3      0.00     0.00
> ".Call"                      2136.90     99.11 1462651.2    178.94     8.30
> "ape::chronos"               2106.74     97.72 1449217.8      0.04     0.00
> "nlminb"                     2106.64     97.71 1449153.4      0.00     0.00
> "objective"                  1956.86     90.76 1361843.4     24.06     1.12
> "penal.loglik"               1932.80     89.65 1342413.7     17.74     0.82
> "log.lik.poisson"            1915.06     88.82 1329046.2   1519.14    70.46
> "isTRUE"                      327.86     15.21  242734.2    266.36    12.35
> "sum"                          68.62      3.18   54134.5     68.62     3.18
> "any"                          56.26      2.61   44924.9     56.26     2.61
> "FUN"                          47.28      2.19   22945.5      0.02     0.00
> "lapply"                       47.20      2.19   22917.7      0.00     0.00
> "phangorn::bootstrap.pml"      47.10      2.18   22886.5      0.00     0.00
> "<Anonymous>"                  47.06      2.18   22880.2      0.40     0.02
> "do.call"                      47.06      2.18   22880.2      0.00     0.00
> "optimRooted"                  46.96      2.18   22852.4      0.84     0.04
> "opt_Edge"                     46.96      2.18   22852.4      0.00     0.00
> "pml.fit4"                     34.82      1.62   16211.9      4.94     0.23
> "optimize"                     28.86      1.34   14485.0      0.22     0.01
> "f"                            27.92      1.29   13956.3      2.46     0.11
> ".External2"                   24.68      1.14   12219.5      0.24     0.01
> "optRoot0"                      9.24      0.43    4384.5      0.52     0.02
> "pml.move"                      4.56      0.21    2290.2      0.52     0.02
> "is.na"                         3.42      0.16    2584.7      3.42     0.16
> "$"                             2.48      0.12    1395.3      2.48     0.12
> "scaleEdges"                    2.08      0.10     471.0      0.00     0.00
> "length"                        1.98      0.09    1540.3      1.98     0.09
> "getDensel"                     1.88      0.09     982.4      0.04     0.00
> "which"                         1.72      0.08     863.5      1.40     0.06
> "density.default"               1.36      0.06     685.2      0.14     0.01
> "stats::density"                1.36      0.06     685.2      0.00     0.00
> "getCallingDLLe"                1.10      0.05     636.2      0.56     0.03
> "$<-"                           0.76      0.04     398.7      0.76     0.04
> "as.double"                     0.60      0.03     294.4      0.60     0.03
> "get0"                          0.50      0.02     277.5      0.50     0.02
> "attr"                          0.44      0.02     243.5      0.44     0.02
> "structure"                     0.44      0.02     251.2      0.04     0.00
> "rle"                           0.34      0.02     206.4      0.16     0.01
> "approx"                        0.34      0.02     185.9      0.10     0.00
> "isUnimodal"                    0.34      0.02     207.0      0.02     0.00
> "diff"                          0.26      0.01     158.1      0.04     0.00
> "fft"                           0.24      0.01     130.9      0.24     0.01
> "dnorm"                         0.20      0.01      95.2      0.20     0.01
> "regularize.values"             0.20      0.01     106.1      0.02     0.00
> "quantile.default"              0.20      0.01      91.6      0.00     0.00
> "pmax.int"                      0.16      0.01      78.4      0.16     0.01
> "seq.int"                       0.16      0.01      63.3      0.16     0.01
> "unique"                        0.16      0.01      80.3      0.04     0.00
> "cbind"                         0.14      0.01      54.8      0.14     0.01
> "unique.default"                0.12      0.01      50.9      0.12     0.01
> "IQR"                           0.12      0.01      63.9      0.00     0.00
> "quantile"                      0.12      0.01      63.9      0.00     0.00
> "stats::bw.nrd0"                0.12      0.01      63.9      0.00     0.00
> "c"                             0.10      0.00      40.2      0.10     0.00
> "pml.fit"                       0.10      0.00      23.6      0.00     0.00
> "diff.default"                  0.08      0.00      53.6      0.08     0.00
> "stopifnot"                     0.08      0.00      37.8      0.06     0.00
> "Cdensel"                       0.08      0.00      22.7      0.04     0.00
> "pmax"                          0.08      0.00      37.6      0.04     0.00
> "apply"                         0.08      0.00      27.7      0.00     0.00
> "update.pml"                    0.08      0.00      14.4      0.00     0.00
> "as.integer"                    0.06      0.00      44.3      0.06     0.00
> "match.arg"                     0.06      0.00      35.9      0.04     0.00
> "deparse"                       0.06      0.00      41.4      0.00     0.00
> "deparse1"                      0.06      0.00      41.4      0.00     0.00
> "paste"                         0.06      0.00      41.4      0.00     0.00
> "prop.part"                     0.06      0.00      10.3      0.00     0.00
> "rbl"                           0.06      0.00      38.9      0.00     0.00
> "dim"                           0.04      0.00      24.4      0.04     0.00
> "list"                          0.04      0.00      27.0      0.04     0.00
> "min"                           0.04      0.00      13.8      0.04     0.00
> "reorderRcpp"                   0.04      0.00       2.6      0.04     0.00
> "%in%"                          0.04      0.00      28.5      0.02     0.00
> "paste0"                        0.04      0.00      16.6      0.02     0.00
> "Siblings"                      0.04      0.00      19.1      0.02     0.00
> "sort.int"                      0.04      0.00      26.3      0.02     0.00
> ".reorder_ape"                  0.04      0.00       2.6      0.00     0.00
> "ape::makeNodeLabel"            0.04      0.00       2.6      0.00     0.00
> "format_perc"                   0.04      0.00      16.6      0.00     0.00
> "makeNodeLabel.phylo"           0.04      0.00       2.6      0.00     0.00
> "reorder.multiPhylo"            0.04      0.00       2.6      0.00     0.00
> "reorder"                       0.04      0.00       2.6      0.00     0.00
> "sort.default"                  0.04      0.00      26.3      0.00     0.00
> "sort"                          0.04      0.00      26.3      0.00     0.00
> "update"                        0.04      0.00       6.3      0.00     0.00
> ".deparseOpts"                  0.02      0.00      13.0      0.02     0.00
> "all"                           0.02      0.00      13.4      0.02     0.00
> "allChildrenCPP"                0.02      0.00       9.6      0.02     0.00
> "cumsum"                        0.02      0.00       0.0      0.02     0.00
> "double"                        0.02      0.00       0.0      0.02     0.00
> "eval"                          0.02      0.00      13.0      0.02     0.00
> "match.fun"                     0.02      0.00      12.7      0.02     0.00
> "minEdge"                       0.02      0.00       2.6      0.02     0.00
> "mode"                          0.02      0.00      14.7      0.02     0.00
> "pairlist"                      0.02      0.00       7.9      0.02     0.00
> "pmin"                          0.02      0.00      12.2      0.02     0.00
> "prop_part2"                    0.02      0.00       7.7      0.02     0.00
> "storage.mode"                  0.02      0.00      11.0      0.02     0.00
> "allChildren"                   0.02      0.00       9.6      0.00     0.00
> "ape::drop.tip"                 0.02      0.00       7.7      0.00     0.00
> "ape::root"                     0.02      0.00       7.7      0.00     0.00
> "formatC"                       0.02      0.00      11.0      0.00     0.00
> "pml.control"                   0.02      0.00       9.9      0.00     0.00
> "root.phylo"                    0.02      0.00       7.7      0.00     0.00
> "vapply"                        0.02      0.00      12.7      0.00     0.00
> 
> $sample.interval
> [1] 0.02
> 
> $sampling.time
> [1] 2156
> ```

**Comment by josephwb** [comment]
Can I leave this to you @KlausVigo to accept/reject?

**Comment by KlausVigo** [comment]
Hi @amizeranschi  & @josephwb, 
seems all fine!

**Pull request closed without merging**
